# -*- mode: shell-script -*-
#
# Control a VMware system using python-pyvmomi.

# Exit with failure message.
# Parameters: exit code, and error message.
fail() {
    echo "$2" >&2
    exit $1
}

issue_vmware_command() {
python - << END
import sys
from provisioningserver.drivers.hardware.vmware import power_control_vmware
try:
    power_control_vmware(
        {{escape_py_literal(power_address) | safe}},
        {{escape_py_literal(power_user) | safe}},
        {{escape_py_literal(power_pass) | safe}},
        {{escape_py_literal(power_vm_name) | safe}},
        {{escape_py_literal(power_uuid) | safe}},
        {{escape_py_literal(power_change) | safe}},
        port={{escape_py_literal(power_port) | safe}},
        protocol={{escape_py_literal(power_protocol) | safe}}
    )
except Exception as e:
    # This gets in the node event log: print the exception's message
    # and not the stacktrace.
    print(unicode(e))
    sys.exit(1)
END
}

query_state() {
python - << END
import sys
from provisioningserver.drivers.hardware.vmware import power_query_vmware
try:
    print(power_query_vmware(
        {{escape_py_literal(power_address) | safe}},
        {{escape_py_literal(power_user) | safe}},
        {{escape_py_literal(power_pass) | safe}},
        {{escape_py_literal(power_vm_name) | safe}},
        {{escape_py_literal(power_uuid) | safe}},
        port={{escape_py_literal(power_port) | safe}},
        protocol={{escape_py_literal(power_protocol) | safe}}
    ))
except Exception as e:
    # This gets in the node event log: print the exception's message
    # and not the stacktrace.
    print(unicode(e))
    sys.exit(1)
END
}

main() {
    case $1 in
    'on'|'off')
        issue_vmware_command
        ;;
    'query')
        query_state
        ;;
    *)
        fail 2 "Unknown power command: '$1'"
    esac
}

main "{{power_change}}"
